/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import business.Employee;
import java.io.File;
import java.text.DateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Admin
 */
public class CreatePanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePanel
     */
    Employee employee;
    ArrayList<Employee> employeeList;

    public CreatePanel(ArrayList employeeList) {
        initComponents();
        this.employee = new Employee();
        this.employeeList = employeeList;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        create_label = new javax.swing.JLabel();
        name_lbl = new javax.swing.JLabel();
        employeeId_lbl = new javax.swing.JLabel();
        age_lbl = new javax.swing.JLabel();
        gender_lbl = new javax.swing.JLabel();
        startDate_lbl = new javax.swing.JLabel();
        level_lbl = new javax.swing.JLabel();
        teamInfo_lbl = new javax.swing.JLabel();
        positionTitle_lbl = new javax.swing.JLabel();
        cellNum_lbl = new javax.swing.JLabel();
        email_lbl = new javax.swing.JLabel();
        name_textField = new javax.swing.JTextField();
        empId_textField = new javax.swing.JTextField();
        age_textField = new javax.swing.JTextField();
        level_textField = new javax.swing.JTextField();
        teamInfo_textField = new javax.swing.JTextField();
        positionTitle_textField = new javax.swing.JTextField();
        cellNum_textField = new javax.swing.JTextField();
        email_textField = new javax.swing.JTextField();
        createProfile_btn = new javax.swing.JButton();
        image_lbl = new javax.swing.JLabel();
        browseImage_btn = new javax.swing.JButton();
        genderComboBox = new javax.swing.JComboBox<>();
        dateChooser = new com.toedter.calendar.JDateChooser();
        numberCheckBtn = new javax.swing.JButton();
        emailCheckBtn = new javax.swing.JButton();

        create_label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        create_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        create_label.setText("Create Employee Profile ");

        name_lbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        name_lbl.setText("Name:");

        employeeId_lbl.setText("Employee ID:");

        age_lbl.setText("Age:");

        gender_lbl.setText("Gender:");

        startDate_lbl.setText("Start Date: ");

        level_lbl.setText("Level:");

        teamInfo_lbl.setText("Team Information:");

        positionTitle_lbl.setText("Position Title:");

        cellNum_lbl.setText("Cell Phone Number:");

        email_lbl.setText("Email Address: ");

        name_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_textFieldActionPerformed(evt);
            }
        });

        createProfile_btn.setText("Create Profile");
        createProfile_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createProfile_btnActionPerformed(evt);
            }
        });

        browseImage_btn.setText("Browse Image");
        browseImage_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseImage_btnActionPerformed(evt);
            }
        });

        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male", "Other" }));

        numberCheckBtn.setText("cell phone check");
        numberCheckBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberCheckBtnActionPerformed(evt);
            }
        });

        emailCheckBtn.setText("email check");
        emailCheckBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailCheckBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(147, 147, 147)
                                .addComponent(name_lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(name_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(age_lbl)
                                    .addComponent(employeeId_lbl)
                                    .addComponent(gender_lbl)
                                    .addComponent(startDate_lbl)
                                    .addComponent(level_lbl)
                                    .addComponent(teamInfo_lbl)
                                    .addComponent(positionTitle_lbl)
                                    .addComponent(cellNum_lbl)
                                    .addComponent(email_lbl))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(empId_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(email_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(emailCheckBtn))
                                            .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(level_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(teamInfo_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(age_textField, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(genderComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(positionTitle_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cellNum_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(numberCheckBtn)))))
                                .addGap(45, 45, 45)))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(image_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(browseImage_btn)
                                .addGap(26, 26, 26))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(createProfile_btn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(create_label, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(create_label, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(name_lbl)
                            .addComponent(name_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(employeeId_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empId_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(age_lbl)
                            .addComponent(age_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gender_lbl)
                            .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(startDate_lbl)
                            .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(level_lbl)
                            .addComponent(level_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(teamInfo_lbl)
                            .addComponent(teamInfo_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(positionTitle_lbl)
                            .addComponent(positionTitle_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cellNum_lbl)
                            .addComponent(cellNum_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numberCheckBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(email_lbl)
                            .addComponent(email_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailCheckBtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(image_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(browseImage_btn)))
                .addGap(18, 18, 18)
                .addComponent(createProfile_btn)
                .addContainerGap(72, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void name_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_textFieldActionPerformed

    private void createProfile_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createProfile_btnActionPerformed
        // TODO add your handling code here:
        
        //converting ID in string form to integer 
        int id = Integer.parseInt(empId_textField.getText());
        //converting age in string form to integer
        int age = Integer.parseInt(age_textField.getText());
        
        //checking if the age entered is a correct age or not 
        if(age<0 || age>100){
            JOptionPane.showMessageDialog(this, "Enter a valid age");
        }
        
        employee.setName(name_textField.getText());
        employee.setEmployee_ID(id);
        employee.setAge(age);
        
        String gender = String.valueOf(genderComboBox.getSelectedItem());
        employee.setGender(gender);
       
        Date date = dateChooser.getDate();
        String strDate = DateFormat.getDateInstance().format(date);
       
        employee.setStart_Date(strDate);
       
        //employee.setStart_Date();
        employee.setLevel(level_textField.getText());
        employee.setTeam_info(teamInfo_textField.getText());
        employee.setPosition_Title(positionTitle_textField.getText());
        
        String email = email_textField.getText();
        boolean validity = emailValid(email);
        
        if(validity == false){
            JOptionPane.showMessageDialog(this, "Employee profile cannot be created. Enter a valid email address");
        }
        
        String cellNumber = cellNum_textField.getText();
        boolean cellPhoneValidity = phoneNumberValid(cellNumber);

        if(cellPhoneValidity == false){
            JOptionPane.showMessageDialog(this, "Enter a valid phone number. Employee profile cannot be created");
        }       
        
        if(validity == true && cellPhoneValidity ==true && (age>0 && age<=100)){
            employee.setCellPhoneNumber(cellNum_textField.getText());
            employee.setEmailAddr(email_textField.getText()); 
            employeeList.add(employee);
            JOptionPane.showMessageDialog(this, "Employee profile is created");
        }
    }//GEN-LAST:event_createProfile_btnActionPerformed

    private void browseImage_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseImage_btnActionPerformed
        // TODO add your handling code here:
        JFileChooser browseImageFile = new JFileChooser();
        
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("IMAGE", "png", "jpeg", "jpg");
        browseImageFile.addChoosableFileFilter(fnef);
        int showOpenDialogue = browseImageFile.showOpenDialog(null);
        
        if(showOpenDialogue == JFileChooser.APPROVE_OPTION){
            File selectedImageFile = browseImageFile.getSelectedFile();
            String selectedImagePath = selectedImageFile.getAbsolutePath();
            JOptionPane.showMessageDialog(null, selectedImagePath);
            
            employee.setImageFilePath(selectedImagePath);
            
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(selectedImagePath).getImage().getScaledInstance(image_lbl.getWidth(), image_lbl.getHeight(), 1));
            image_lbl.setIcon(imageIcon);
        }
        
        
    }//GEN-LAST:event_browseImage_btnActionPerformed

    private void numberCheckBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberCheckBtnActionPerformed
        // TODO add your handling code here:
        String cellNumber = cellNum_textField.getText();
        boolean validity = phoneNumberValid(cellNumber);
        
        if(validity == true){
            employee.setCellPhoneNumber(cellNumber);
            JOptionPane.showMessageDialog(this, "Valid Phone Number");
        }
        else{
            JOptionPane.showMessageDialog(null, "Invalid phone number. Enter again.","Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_numberCheckBtnActionPerformed

    private void emailCheckBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailCheckBtnActionPerformed
        // TODO add your handling code here:
        String email = email_textField.getText();
        boolean validity = emailValid(email);
        
        if(validity == true){
            employee.setEmailAddr(email);
            JOptionPane.showMessageDialog(this, "Valid Address");
        }
        else{
            JOptionPane.showMessageDialog(null, "Invalid Email Address. Enter Again.","Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_emailCheckBtnActionPerformed

    public boolean phoneNumberValid(String phoneNumber){
        
        String regex = "^\\(?([0-9]{3})\\)?[-.\\s]?([0-9]{3})[-.\\s]?([0-9]{4})$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(phoneNumber);
        
        return matcher.matches();
    }
    
    public boolean emailValid(String emailAdd){
        String regex = "^(?=.{1,64}@)[A-Za-z0-9_-]+(\\.[A-Za-z0-9_-]+)*@" 
        + "[^-][A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z]{2,})$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(emailAdd);
        
        return matcher.matches();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel age_lbl;
    private javax.swing.JTextField age_textField;
    private javax.swing.JButton browseImage_btn;
    private javax.swing.JLabel cellNum_lbl;
    private javax.swing.JTextField cellNum_textField;
    private javax.swing.JButton createProfile_btn;
    private javax.swing.JLabel create_label;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JButton emailCheckBtn;
    private javax.swing.JLabel email_lbl;
    private javax.swing.JTextField email_textField;
    private javax.swing.JTextField empId_textField;
    private javax.swing.JLabel employeeId_lbl;
    private javax.swing.JComboBox<String> genderComboBox;
    private javax.swing.JLabel gender_lbl;
    private javax.swing.JLabel image_lbl;
    private javax.swing.JLabel level_lbl;
    private javax.swing.JTextField level_textField;
    private javax.swing.JLabel name_lbl;
    private javax.swing.JTextField name_textField;
    private javax.swing.JButton numberCheckBtn;
    private javax.swing.JLabel positionTitle_lbl;
    private javax.swing.JTextField positionTitle_textField;
    private javax.swing.JLabel startDate_lbl;
    private javax.swing.JLabel teamInfo_lbl;
    private javax.swing.JTextField teamInfo_textField;
    // End of variables declaration//GEN-END:variables
}
