/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import business.Employee;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */


public class UpdatePanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdatePanel
     */
    
     ArrayList<Employee> employeeList;
     
    public UpdatePanel(ArrayList employeeList) {
        initComponents();
        this.employeeList = employeeList;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        positionTitle_textField = new javax.swing.JTextField();
        cellNum_textField = new javax.swing.JTextField();
        email_textField = new javax.swing.JTextField();
        create_label = new javax.swing.JLabel();
        name_lbl = new javax.swing.JLabel();
        employeeId_lbl = new javax.swing.JLabel();
        age_lbl = new javax.swing.JLabel();
        gender_lbl = new javax.swing.JLabel();
        startDate_lbl = new javax.swing.JLabel();
        level_lbl = new javax.swing.JLabel();
        teamInfo_lbl = new javax.swing.JLabel();
        positionTitle_lbl = new javax.swing.JLabel();
        cellNum_lbl = new javax.swing.JLabel();
        email_lbl = new javax.swing.JLabel();
        name_textField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        readProfile_textField = new javax.swing.JTextField();
        readProfile_btn = new javax.swing.JButton();
        empId_textField = new javax.swing.JTextField();
        age_textField = new javax.swing.JTextField();
        gender_textField = new javax.swing.JTextField();
        startDate_textField = new javax.swing.JTextField();
        level_textField = new javax.swing.JTextField();
        teamInfo_textField = new javax.swing.JTextField();
        updateProfile_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        genderComboBox = new javax.swing.JComboBox<>();

        create_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        create_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        create_label.setText("Update Employee Profile ");

        name_lbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        name_lbl.setText("Name:");

        employeeId_lbl.setText("Employee ID:");

        age_lbl.setText("Age:");

        gender_lbl.setText("Gender:");

        startDate_lbl.setText("Start Date: ");

        level_lbl.setText("Level:");

        teamInfo_lbl.setText("Team Information:");

        positionTitle_lbl.setText("Position Title:");

        cellNum_lbl.setText("Cell Phone Number:");

        email_lbl.setText("Email Address: ");

        name_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_textFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Enter Employee Id:");

        readProfile_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readProfile_textFieldActionPerformed(evt);
            }
        });

        readProfile_btn.setText("Read Profile");
        readProfile_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readProfile_btnActionPerformed(evt);
            }
        });

        gender_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gender_textFieldActionPerformed(evt);
            }
        });

        updateProfile_btn.setText("Update Profile");
        updateProfile_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateProfile_btnActionPerformed(evt);
            }
        });

        jLabel2.setText("Make Changes here to Update:");

        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male", "Other" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 138, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(create_label, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(235, 235, 235))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(age_lbl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(employeeId_lbl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(gender_lbl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(level_lbl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(startDate_lbl, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(empId_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(170, 170, 170))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(gender_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(age_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(startDate_textField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(level_textField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(name_lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(name_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(172, 172, 172))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(teamInfo_lbl)
                            .addComponent(positionTitle_lbl)
                            .addComponent(cellNum_lbl)
                            .addComponent(email_lbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(positionTitle_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(teamInfo_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cellNum_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(182, 182, 182))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(readProfile_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(readProfile_btn)
                        .addGap(160, 160, 160))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(updateProfile_btn)
                        .addGap(280, 280, 280))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(create_label, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(readProfile_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(readProfile_btn))
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_lbl)
                    .addComponent(name_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeeId_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empId_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(age_lbl)
                    .addComponent(age_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gender_lbl)
                    .addComponent(gender_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startDate_lbl)
                    .addComponent(startDate_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(level_lbl)
                    .addComponent(level_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teamInfo_lbl)
                    .addComponent(teamInfo_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(positionTitle_lbl)
                    .addComponent(positionTitle_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cellNum_lbl)
                    .addComponent(cellNum_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email_lbl)
                    .addComponent(email_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateProfile_btn)
                .addContainerGap(48, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void name_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_textFieldActionPerformed

    private void readProfile_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readProfile_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_readProfile_textFieldActionPerformed

    private void readProfile_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readProfile_btnActionPerformed
        // TODO add your handling code here:
        String y = readProfile_textField.getText();
        displayEmployee(y);
    }//GEN-LAST:event_readProfile_btnActionPerformed

    private void updateProfile_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProfile_btnActionPerformed
        // TODO add your handling code here:
        String y = readProfile_textField.getText();
        Employee employee = new Employee();
         
        int z = Integer.parseInt(y);
        
        for(Employee e: employeeList){
            if(e.getEmployee_ID() == z){
                employee = e;
            }
   
        }
        
        employee.setName(name_textField.getText());
        String q = empId_textField.getText();
        employee.setEmployee_ID(Integer.parseInt(q));
        int ageString = Integer.parseInt(age_textField.getText());
        employee.setAge(ageString);
        String x = String.valueOf(genderComboBox.getSelectedItem());
        employee.setGender(x);
        employee.setStart_Date(startDate_textField.getText());
        employee.setLevel(level_textField.getText());
        employee.setTeam_info(teamInfo_textField.getText());
        employee.setPosition_Title(positionTitle_textField.getText());
        
        employee.setCellPhoneNumber(cellNum_textField.getText());
        employee.setEmailAddr(email_textField.getText()); 
        
        JOptionPane.showMessageDialog(this, "Employee profile is updated");
    }//GEN-LAST:event_updateProfile_btnActionPerformed

    private void gender_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gender_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gender_textFieldActionPerformed

    private void displayEmployee(String y) {
       
        String k = y;
        int z = Integer.parseInt(k);
        
         Employee employee = new Employee();
         
        for(Employee e: employeeList){
            if(e.getEmployee_ID() == z){
                employee = e;
            }
        }
        
        name_textField.setText(employee.getName());
        String q = Integer.toString(employee.getEmployee_ID());
        empId_textField.setText(q);
        String ageString = String.valueOf(employee.getAge());
        age_textField.setText(ageString);
        gender_textField.setText(employee.getGender());
        startDate_textField.setText(employee.getStart_Date());
        level_textField.setText(employee.getLevel());
        teamInfo_textField.setText(employee.getTeam_info());
        positionTitle_textField.setText(employee.getPosition_Title());
        cellNum_textField.setText(employee.getCellPhoneNumber());
        email_textField.setText(employee.getEmailAddr());
        
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel age_lbl;
    private javax.swing.JTextField age_textField;
    private javax.swing.JLabel cellNum_lbl;
    private javax.swing.JTextField cellNum_textField;
    private javax.swing.JLabel create_label;
    private javax.swing.JLabel email_lbl;
    private javax.swing.JTextField email_textField;
    private javax.swing.JTextField empId_textField;
    private javax.swing.JLabel employeeId_lbl;
    private javax.swing.JComboBox<String> genderComboBox;
    private javax.swing.JLabel gender_lbl;
    private javax.swing.JTextField gender_textField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel level_lbl;
    private javax.swing.JTextField level_textField;
    private javax.swing.JLabel name_lbl;
    private javax.swing.JTextField name_textField;
    private javax.swing.JLabel positionTitle_lbl;
    private javax.swing.JTextField positionTitle_textField;
    private javax.swing.JButton readProfile_btn;
    private javax.swing.JTextField readProfile_textField;
    private javax.swing.JLabel startDate_lbl;
    private javax.swing.JTextField startDate_textField;
    private javax.swing.JLabel teamInfo_lbl;
    private javax.swing.JTextField teamInfo_textField;
    private javax.swing.JButton updateProfile_btn;
    // End of variables declaration//GEN-END:variables
}
